const OsramClient = require('./lib/osramclient');
const util = require('./lib/util');

// console.log(util.generateCommand('FE0E050202d37a038800dd0000'));

const osramclient = new OsramClient();
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());
osramclient.getBulbState('d37a', '03', () => console.log());